import 'package:get/get.dart';
import 'package:macro_cal_public/models/activity.dart';
import 'package:macro_cal_public/models/historical_measurement.dart';
import 'package:macro_cal_public/models/ingredient.dart';

class DataController extends GetxController {
  RxBool isUserLogedIn = true.obs;

  RxList<Ingredient> ingredientsList = RxList([
    Ingredient(
      referenceQuantity: 100.0,
      ingridientName: "Γάλα 1.5%",
      category: "Dairy",
      calories: 45.0,
      proteins: 3.2,
      carbohydrates: 4.5,
      sugars: 4.5,
      fats: 1.5,
      saturated: 1.0,
      fiber: 0.0,
      salt: 50,
    ),
    Ingredient(
      ingridientName: 'Yogurt 2%',
      category: "Dairy",
      referenceQuantity: 100.0,
      calories: 66.0,
      proteins: 8.0,
      carbohydrates: 3.9,
      sugars: 3.9,
      fats: 2.0,
      saturated: 1.4,
      fiber: 0.0,
      salt: 160,
    ),
    Ingredient(
      ingridientName: 'Cream Yogurt Lidl',
      category: "Dairy",
      referenceQuantity: 100.0,
      calories: 105,
      proteins: 3.1,
      carbohydrates: 13.4,
      sugars: 11.6,
      fats: 4.3,
      saturated: 2.8,
      fiber: 0.0,
      salt: 130,
    ),
    Ingredient(
      referenceQuantity: 100.0,
      ingridientName: "Κεφίρ Μεβγάλ Φράουλα",
      category: "Dairy",
      calories: 48.0,
      proteins: 3.1,
      carbohydrates: 6,
      sugars: 6,
      fats: 1.3,
      saturated: 0.9,
      fiber: 0.0,
      salt: 110,
    ),
    Ingredient(
      referenceQuantity: 100.0,
      ingridientName: "Κεφίρ Κουκάκη φράουλα",
      category: "Dairy",
      calories: 59.0,
      proteins: 3,
      carbohydrates: 8,
      sugars: 7.3,
      fats: 1.7,
      saturated: 1.2,
      fiber: 0.0,
      salt: 90,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Ψωμι Τοστ Χωρ/νο",
      category: "Grain-based",
      calories: 254,
      proteins: 11,
      carbohydrates: 41,
      sugars: 4.6,
      fats: 4.0,
      saturated: 0.7,
      fiber: 5,
      salt: 1400,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "WASA",
      category: "Grain-based",
      calories: 340,
      proteins: 9,
      carbohydrates: 61,
      sugars: 1.5,
      fats: 1.5,
      saturated: 0.4,
      fiber: 20,
      salt: 1000,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Cottage 4%",
      category: "Dairy",
      calories: 96,
      proteins: 13.0,
      carbohydrates: 1.3,
      sugars: 1,
      fats: 4.0,
      saturated: 2.5,
      fiber: 0.0,
      salt: 400,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Gouda Low Fat",
      category: "Cheese",
      calories: 270,
      proteins: 28,
      carbohydrates: 0,
      sugars: 0,
      fats: 18.0,
      saturated: 12.0,
      fiber: 0.0,
      salt: 1800,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Γαλοπουλα Βραστη",
      category: 'Processed Meat',
      calories: 100,
      proteins: 15,
      carbohydrates: 5.4,
      sugars: 1.2,
      fats: 1,
      saturated: 0.4,
      fiber: 0.0,
      salt: 2400,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Δημητριακά Ολικής",
      category: "Grain-based",
      calories: 380,
      proteins: 8.9,
      carbohydrates: 79.5,
      sugars: 8.8,
      fats: 1.8,
      saturated: 0.3,
      fiber: 8.1,
      salt: 520,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Αυγά Μέτρια",
      category: "Protein Based",
      calories: 138,
      proteins: 13,
      carbohydrates: 1,
      sugars: 0,
      fats: 11,
      saturated: 3.2,
      fiber: 0,
      salt: 300,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Ελαιόλαδο",
      category: "Fatty products",
      calories: 828,
      proteins: 0,
      carbohydrates: 0,
      sugars: 0,
      fats: 92,
      saturated: 14,
      fiber: 0,
      salt: 0,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Φυστικοβούτηρο Lidl",
      category: "Fatty products",
      calories: 654,
      proteins: 27.8,
      carbohydrates: 10,
      sugars: 6.1,
      fats: 55,
      saturated: 12,
      fiber: 5,
      salt: 0,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Φυστικοβούτηρο Γαλάζιο",
      category: "Fatty products",
      calories: 610,
      proteins: 22.1,
      carbohydrates: 15.9,
      sugars: 7.2,
      fats: 49.3,
      saturated: 8.3,
      fiber: 7.4,
      salt: 600,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Μήλο",
      category: 'Fruits',
      calories: 56,
      proteins: 0.2,
      carbohydrates: 13,
      sugars: 9.5,
      fats: 0.2,
      saturated: 0,
      fiber: 2.5,
      salt: 0,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Chicken Breast (Raw)",
      category: "Meats",
      calories: 165,
      proteins: 31.0,
      carbohydrates: 0.0,
      sugars: 0.0,
      fats: 3.6,
      saturated: 1.0,
      fiber: 0.0,
      salt: 74,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Chicken Thigh (Raw)",
      category: "Meats",
      calories: 180,
      proteins: 16.0,
      carbohydrates: 0.0,
      sugars: 0.0,
      fats: 13.0,
      saturated: 3.5,
      fiber: 0.0,
      salt: 60,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "French Fries",
      category: "Fried",
      calories: 330,
      proteins: 3.7,
      carbohydrates: 38,
      sugars: 0.5,
      fats: 17.0,
      saturated: 4,
      fiber: 3.5,
      salt: 200,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Ice Cream",
      category: "Sweets & Chocolate",
      calories: 207,
      proteins: 3.9,
      carbohydrates: 26.0,
      sugars: 23.0,
      fats: 10.9,
      saturated: 6.8,
      fiber: 0.0,
      salt: 56,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: 'Lila Pause',
      category: "Sweets & Chocolate",
      calories: 545,
      proteins: 4.8,
      carbohydrates: 58,
      sugars: 54,
      fats: 32,
      saturated: 18,
      fiber: 1.1,
      salt: 560,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Kinder Choc. Bars 8",
      category: "Sweets & Chocolate",
      calories: 546,
      proteins: 8.6,
      carbohydrates: 51.5,
      sugars: 51.5,
      fats: 33.8,
      saturated: 21.5,
      fiber: 0.4,
      salt: 30,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Chicken Sandwitch tortiya",
      category: "Fast Complex Meals",
      calories: 205,
      proteins: 12.9,
      carbohydrates: 24.6,
      sugars: 1.4,
      fats: 6.1,
      saturated: 1.1,
      fiber: 0.4,
      salt: 30,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "τυροκαφτερη αμβροσια",
      category: "Smears",
      calories: 219,
      proteins: 8.2,
      carbohydrates: 4.6,
      sugars: 2.3,
      fats: 18.6,
      saturated: 3.3,
      fiber: 0,
      salt: 2000,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Lidl Dumblings",
      category: "Fast Complex Meals",
      calories: 216,
      proteins: 6.8,
      carbohydrates: 32.6,
      sugars: 0.9,
      fats: 6.4,
      saturated: 2.9,
      fiber: 0,
      salt: 900,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Κεφαλοτύρι",
      category: "Cheese",
      calories: 355,
      proteins: 25,
      carbohydrates: 0,
      sugars: 0,
      fats: 29,
      saturated: 18,
      fiber: 0,
      salt: 2100,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Nestle Fitness Μπάρες",
      category: "Grain-based",
      calories: 380,
      proteins: 6.7,
      carbohydrates: 69.7,
      sugars: 24.5,
      fats: 7.7,
      saturated: 3.0,
      fiber: 5.5,
      salt: 610,
    ),
    Ingredient(
      referenceQuantity: 100,
      ingridientName: "Mary's Cookies",
      category: "Sweets & Chocolate",
      calories: 365,
      proteins: 4.5,
      carbohydrates: 60,
      sugars: 59,
      fats: 12.5,
      saturated: 9,
      fiber: 0.3,
      salt: 520,
    ),
  ]);

  RxList<int> ingredientQuantitiesList = RxList([
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
  ]);

  RxList<Activity> activitiesList = RxList([
    Activity(
      activityName: 'Walking',
      caloryConsumptionPerUnit: 50,
      metricDescription: 'Kilometers',
      isMetricBasedOnDuration: false,
    ),
  ]);

  RxList<int> activitiyVolumesList = RxList([0]);

  RxList<HistoricalMeasurement> historicalMeasurementsList = RxList([]);

  //Today's Page
  RxDouble adjustedCalories = 0.0.obs;
  RxDouble dailyCalories = 2100.0.obs;
  RxDouble dailyProteins = 100.0.obs;
  RxDouble dailyCarbs = 175.0.obs;
  RxDouble dailyFats = 78.0.obs;
  RxDouble dailyFiber = 35.0.obs;
  RxDouble sugarsLimit = 10.0.obs;
  RxDouble saturatedLimit = 8.0.obs;
  RxDouble sodiumLimit = 5800.0.obs;
  RxDouble consumedCalories = 0.0.obs;
  RxDouble proteinConsumed = 0.0.obs;
  RxDouble carbsConsumed = 0.0.obs;
  RxDouble fiberConsumed = 0.0.obs;
  RxDouble fatsConsumed = 0.0.obs;
  RxDouble sugarsConsumed = 0.0.obs;
  RxDouble saturatedConsumed = 0.0.obs;
  RxDouble sodiumConsumed = 0.0.obs;

  //Profile
  RxDouble bodyWeight = 94.0.obs;
  RxDouble bodyHeight = 184.0.obs;
}
